name: deployment

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on:
      - self-hosted
      - dev-server

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apartment-api:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/apartment-api:latest

  pull:
    needs: build
    runs-on:
      - self-hosted
      - dev-server
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/apartment-api:latest

  deploy:
    needs: pull
    runs-on:
      - self-hosted
      - dev-server

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Docker compose
        run: docker-compose -f "docker-compose.yml" up -d
